#include "nsISupports.idl"

[scriptable, uuid(8fdcb7bc-43ed-462e-979d-4a746f9b223c)]
interface nsIIeTab : nsISupports
{
   void updateAll();
   void addIeTab(in wstring url);
   void loadIeTab(in wstring url);
   void closeIeTab();
   void onProgressChange(in long progress);
   void onSecurityChange(in long security);
};

[scriptable, uuid(c36b7d1b-5818-42b2-965c-f5851f6f1122)]
interface nsIIETabPlugin : nsISupports
{
  attribute nsISupports requestTarget;
  readonly attribute boolean canClose;

  readonly attribute boolean canBack;
  boolean goBack();
  readonly attribute boolean canForward;
  boolean goForward();
  boolean navigate(in wstring url);
  readonly attribute boolean canRefresh;
  boolean refresh();
  readonly attribute boolean canStop;
  boolean stop();

  readonly attribute long progress;
  readonly attribute long security;

  readonly attribute wstring url;
  readonly attribute wstring title;

  boolean saveAs();
  boolean print();
  boolean printPreview();
  boolean printSetup();

  readonly attribute boolean canCut;
  boolean cut();

  readonly attribute boolean canCopy;
  boolean copy();

  readonly attribute boolean canPaste;
  boolean paste();

  boolean selectAll();
  boolean find();

  boolean viewSource();

  void focus();
};
